---
title: "Basics"
format: 
  html:
    code-copy: false
---
<html>
<head>
    <style>
        body {
            -webkit-user-select: none; /* Safari */
            -moz-user-select: none; /* Firefox */
            -ms-user-select: none; /* IE10+/Edge */
            user-select: none; /* Standard */
        }
    </style>
</head>
<body>

:::{.callout-note}
**Referencing the content on this webpage:**

Bulusu, Kartik V. (2025, January). MAE 6291: Internet-of-Things for Engineers. [Course lecture notes, codes and presentations]. Department of Mechanical and Aerospace Engineering, The George Washington University.
:::

<!-- Schedule [*week-by-week*]

::: {.callout-warning appearance="simple"}
**The course schedule below will be updated on a weekly basis during the Spring 2025 semester.**
::: -->

<!-- ::: {.callout-important appearance="default" title="Final Project Due Date"}
The Final Project deliverables are due on **December 05, 2023, 11:59 PM**. Check-out the schedule to learn more about where to [submit all the deliverables](schedule.qmd#final-project).
::: -->

<style>
        .thumbnail {
            width: 100px; 
            cursor: pointer;
        }

        #popupContainer {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.7);
            justify-content: center;
            align-items: center;
        }

        #popupImage {
            max-width: 80%;
            max-height: 80%;
        }
    </style>

<table class="table table-hover w-auto">
  <colgroup>
    <col style="width:30%">
    <col style="width:50%">
    <col style="width:20%">
    <!-- <col style="width:32%"> -->
  </colgroup>
  <thead>
    <tr>
      <th scope="col">Topic(s) </th>
      <th scope="col">Description </th>
      <th scope="col">Slide deck(s) </th>
      <!--- <th scope="col">Column heading</th> -->
    </tr>
  </thead>
  <tbody>
    <tr class="table-secondary">
      <th scope="row">Your First Program</th>
        <td>
            desc here
        </td>
        <td>
            <a href="./unit0/modules/module0.qmd">Module 0 </a> <br><br>
            <a href="./unit0/modules/module1.qmd">Module 1 </a>
        </td>
    </tr>
    <!-- <tr class="table-secondary">
      <th scope="row">A few more getting started examples</th>
        <td>
            desc here
        </td>
        <td>
            <a href="./unit0/modules/module1.qmd">Module 1 </a>
        </td>
    </tr> -->
    <tr class="table-secondary">
      <th scope="row">Booleans, string, built-in functions & types</th>
        <td>
            desc here
        </td>
        <td>
            <a href="./unit1/modules/module3.qmd">Module 2 </a>
        </td>
    </tr>
    <tr class="table-secondary">
      <th scope="row">Integers & Real Number</th>
        <td>
            desc here
        </td>
        <td>
            <a href="./unit0/modules/module4.qmd">Module 4 </a> <br><br>
            <a href="./unit0/modules/module6.qmd">Module 6 </a>
        </td>
    </tr>
    <tr class="table-secondary">
      <th scope="row">Strings & Characters</th>
        <td>
            desc here
        </td>
        <td>
            <a href="./unit0/modules/module5.qmd">Module 5 </a>
        </td>
    </tr>
  </tbody>
</table>

